# Generated by Django 2.0.2 on 2018-02-27 16:07

from django.contrib.sites.models import Site
from django.conf import settings
from django.db import migrations


def fix_site_name_domain(apps, schema_editor):
    site = Site.objects.get(pk=1)
    site.domain = settings.FRONTEND_SITE_DOMAIN
    site.name = settings.FRONTEND_SITE_NAME
    site.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(fix_site_name_domain),
    ]
