export const UI = {
  DARK_THEME: 'UI_DARK_THEME',
  LANGUAGE: 'UI_LANGUAGE',
  SIDEBAR_VISIBLE: 'UI_SIDEBAR_VISIBLE',
  SETTINGS_VISIBLE: 'UI_SETTINGS_VISIBLE',
  NAVBAR_COLOR: 'UI_NAVBAR_COLOR',
  PROGRESS_START: 'UI_PROGRESS_START',
  PROGRESS_STOP: 'UI_PROGRESS_STOP',
  PROGRESS_FAIL: 'UI_PROGRESS_FAIL'
}

export const USER = {
  FETCH_DATA: 'USER_FETCH_DATA',
  LOGOUT: 'USER_LOGOUT'
}
