export const UI = {
  DARK_THEME: 'UI_DARK_THEME',
  SIDEBAR_STATUS: 'UI_SIDEBAR_STATUS',
  NAVBAR_COLOR: 'UI_NAVBAR_COLOR'
}

export const USER = {
  FETCH_DATA: 'USER_FETCH_DATA',
  LOGOUT: 'USER_LOGOUT'
}
